-- Firms Tables

DROP TABLE IF EXISTS world_sim_firms.firm_states;
DROP TABLE IF EXISTS world_sim_firms.firms;

CREATE TABLE world_sim_firms.firms (
    id VARCHAR(50) PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    industry_code VARCHAR(10),
    address TEXT,
    
    -- DNB Data Fields
    -- for the firms for the time being
    year INT,
    dunsno VARCHAR(20),
    nationalcode VARCHAR(20),
    countycode VARCHAR(10),
    statecode VARCHAR(10),
    citycode VARCHAR(20),
    streetaddress TEXT,
    city VARCHAR(100),
    state VARCHAR(10),
    zipcode VARCHAR(20),
    zipcode4 VARCHAR(10),
    mailingaddresscode VARCHAR(10),
    mailingaddress TEXT,
    mailingcityname VARCHAR(100),
    mailingstate VARCHAR(10),
    mailingzipcode VARCHAR(20),
    mailingzipcode4 VARCHAR(10),
    phonenumber VARCHAR(20),
    principal VARCHAR(255),
    ddm VARCHAR(100),
    businessdescription TEXT,
    yearstarted INT,
    sls DECIMAL(15,2),
    slscode VARCHAR(10),
    employeesthissite INT,
    employeesthissitecode VARCHAR(10),
    employeesallsites INT,
    employeesallsitescode VARCHAR(10),
    sic1 VARCHAR(10),
    sic2 VARCHAR(10),
    sic3 VARCHAR(10),
    sic4 VARCHAR(10),
    sic5 VARCHAR(10),
    sic6 VARCHAR(10),
    secondaryname VARCHAR(255),
    parentcityname VARCHAR(100),
    parentstate VARCHAR(10),
    dandboffice VARCHAR(10),
    hqdunsno VARCHAR(20),
    parentdunsno VARCHAR(20),
    ultdunsno VARCHAR(20),
    status VARCHAR(50),
    subsidiaryindicator VARCHAR(10),
    manufacturing VARCHAR(10),
    salesgrowth DECIMAL(10,4),
    employmentgrowth DECIMAL(10,4),
    smsacode VARCHAR(20),
    baseyearsales DECIMAL(15,2),
    baseyearemployment INT,
    trendyearsales DECIMAL(15,2),
    trendyearemployment INT,
    populationcode VARCHAR(10),
    transactioncode VARCHAR(10),
    hiercode VARCHAR(10),
    diascode VARCHAR(10),
    reportdate DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_firms_industry (industry_code),
    INDEX idx_firms_location (city, state),
    INDEX idx_firms_sic1 (sic1)
);

CREATE TABLE world_sim_firms.firm_states (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    firm_id VARCHAR(50) NOT NULL,
    simulation_id VARCHAR(64),
    cash DECIMAL(15,2) DEFAULT 0.00,
    inventory JSON,
    prices JSON,
    state_data JSON,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_firm_sim (firm_id, simulation_id),
    INDEX idx_simulation (simulation_id)
);

