-- Simulations Tables


DROP DATABASE IF EXISTS world_sim_simulations;
CREATE DATABASE world_sim_simulations CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- removing the tables if they are already there so that we can recreate them
DROP TABLE IF EXISTS world_sim_simulations.plan_steps;
DROP TABLE IF EXISTS world_sim_simulations.plans;
DROP TABLE IF EXISTS world_sim_simulations.transactions;
DROP TABLE IF EXISTS world_sim_simulations.events;
DROP TABLE IF EXISTS world_sim_simulations.action_ledger;
DROP TABLE IF EXISTS world_sim_simulations.agent_locations;
DROP TABLE IF EXISTS world_sim_simulations.initialized_agents;
DROP TABLE IF EXISTS world_sim_simulations.simulations;


-- table to store the main simulation information that we have
CREATE TABLE world_sim_simulations.simulations (
    simulation_id VARCHAR(64) NOT NULL PRIMARY KEY,
    started_by VARCHAR(100),
    description TEXT,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP NULL,
    status ENUM('running', 'completed', 'failed', 'paused') DEFAULT 'running',
    parameters JSON,
    results JSON,
    simulation_start_datetime DATETIME,
    current_simulation_datetime DATETIME,
    simulation_end_datetime DATETIME,
    tick_granularity VARCHAR(10) DEFAULT '1min',
    config_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status (status),
    INDEX idx_started_by (started_by),
    INDEX idx_start_time (start_time)
);


-- table to store the agents that were initialized in a simulation
CREATE TABLE world_sim_simulations.initialized_agents (
    simulation_id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (simulation_id, agent_id),
    INDEX idx_sim_agent (simulation_id, agent_id),
    FOREIGN KEY (simulation_id) REFERENCES simulations(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);

-- table to store the agent spatial positions at each simulation timestamp
CREATE TABLE world_sim_simulations.agent_locations (
    simulation_id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(64) NOT NULL,
    latitude DECIMAL(10,8) NOT NULL,
    longitude DECIMAL(11,8) NOT NULL,
    simulation_timestamp TIMESTAMP NOT NULL,
    PRIMARY KEY (simulation_id, agent_id, simulation_timestamp),
    INDEX idx_sim_agent_location (simulation_id, agent_id),
    INDEX idx_lat_lon (latitude, longitude),
    FOREIGN KEY (simulation_id) REFERENCES simulations(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);

-- table to store the audit log of all agent actions executed during simulation
CREATE TABLE world_sim_simulations.action_ledger (
    simulation_id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(64) NOT NULL,
    action_name VARCHAR(255) NOT NULL,
    action_params JSON NULL,
    events_generated JSON NULL,
    journal_entries JSON NULL,
    execution_time_ms INT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (simulation_id, agent_id, timestamp),
    INDEX idx_sim_agent_time (simulation_id, agent_id, timestamp),
    INDEX idx_action (action_name),
    INDEX idx_status (status),
    FOREIGN KEY (simulation_id) REFERENCES simulations(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);

-- table to store the simulation events generated by agent actions
CREATE TABLE world_sim_simulations.events (
    simulation_id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    action_name VARCHAR(100),
    execution_time_ms INT,
    status VARCHAR(50),
    action_params JSON,
    event_data JSON,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (simulation_id, agent_id, timestamp),
    INDEX idx_sim_type (simulation_id, event_type),
    INDEX idx_agent (agent_id),
    INDEX idx_timestamp (timestamp),
    FOREIGN KEY (simulation_id) REFERENCES simulations(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);

-- table to store the economic transactions between entities in simulations
CREATE TABLE world_sim_simulations.transactions (
    simulation_id VARCHAR(64) NOT NULL,
    from_entity VARCHAR(64) NOT NULL,
    to_entity VARCHAR(64) NOT NULL,
    transaction_type VARCHAR(100) DEFAULT 'sale',
    amount DECIMAL(15,2),
    item_type VARCHAR(100),
    item_quantity DECIMAL(15,4),
    description TEXT,
    metadata JSON,
    event_id VARCHAR(255),
    idempotency_key VARCHAR(255),
    total_amount DECIMAL(15,2),
    sku VARCHAR(100),
    quantity DECIMAL(15,4),
    source_timestamp TIMESTAMP,
    event_type VARCHAR(100),
    ingest_timestamp TIMESTAMP,
    firm_id VARCHAR(255),
    buyer_type VARCHAR(100),
    seller_type VARCHAR(100),
    use_type VARCHAR(100),
    sector VARCHAR(100),
    subsector VARCHAR(100),
    unit_price DECIMAL(15,2),
    currency VARCHAR(10),
    unit_cost DECIMAL(15,2),
    inventory_method VARCHAR(50),
    is_correction_of VARCHAR(255),
    transaction_status VARCHAR(50) DEFAULT 'completed',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (simulation_id, from_entity, to_entity, transaction_type, source_timestamp),
    INDEX idx_sim_entities (simulation_id, from_entity, to_entity),
    INDEX idx_transaction_type (transaction_type),
    INDEX idx_timestamp (created_at),
    FOREIGN KEY (simulation_id) REFERENCES simulations(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (from_entity) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE,
    FOREIGN KEY (to_entity) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);

-- table to store the agent plans generated for goal-oriented behavior
CREATE TABLE world_sim_simulations.plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    simulation_id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(64) NOT NULL,
    plan_type VARCHAR(50) NOT NULL,
    horizon VARCHAR(50) NOT NULL,
    goal TEXT NOT NULL,
    world_context TEXT,
    status VARCHAR(50) DEFAULT 'draft',
    total_steps INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_sim_agent (simulation_id, agent_id),
    INDEX idx_status (status),
    FOREIGN KEY (simulation_id) REFERENCES simulations(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);

-- table to store the individual steps within agent plans
CREATE TABLE world_sim_simulations.plan_steps (
    simulation_id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(64) NOT NULL,
    plan_id BIGINT UNSIGNED NOT NULL,
    step_order INT NOT NULL,
    target_time VARCHAR(20),
    action VARCHAR(100) NOT NULL,
    location VARCHAR(100),
    status VARCHAR(50) DEFAULT 'pending',
    travel_destination VARCHAR(100),
    exchange_counterparty VARCHAR(255),
    exchange_sku VARCHAR(100),
    exchange_quantity DECIMAL(15,4),
    wait_minutes INT,
    param_key_1 VARCHAR(100),
    param_value_1 VARCHAR(255),
    param_key_2 VARCHAR(100),
    param_value_2 VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (simulation_id, agent_id, plan_id, step_order),
    INDEX idx_plan_order (plan_id, step_order),
    INDEX idx_status (status),
    FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE,
    FOREIGN KEY (simulation_id) REFERENCES plans(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);

-- table to store the household balance sheet samples at simulation timestamps
DROP TABLE IF EXISTS world_sim_simulations.household_balance_sheet_samples;
CREATE TABLE world_sim_simulations.household_balance_sheet_samples (
  
  -- identifiers
  simulation_id VARCHAR(64) NOT NULL,
  household_id VARCHAR(32) NOT NULL,            
  sim_clock_datetime TIMESTAMP NOT NULL,

  -- provenance
  net_worth_bucket VARCHAR(64) NULL,
  hpi_level VARCHAR(32) NULL,
  hpi_place_id VARCHAR(32) NULL,
  vehicle_lambda_decay DECIMAL(6,5) NULL,

  -- ASSETS (USD)
  primaryHomeValue       DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  secondaryREValue       DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  retirementAccounts     DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  taxableInvestments     DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  liquidSavings          DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  vehiclesValue          DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  durablesOther          DECIMAL(18,2) NOT NULL DEFAULT 0.00,

  -- LIABILITIES (USD)
  mortgageBalance        DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  autoLoans              DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  creditCardRevolving    DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  studentLoans           DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  otherDebt              DECIMAL(18,2) NOT NULL DEFAULT 0.00,

  -- TOTALS (store explicitly for speed)
  assetsTotal            DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  liabilitiesTotal       DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  netWorth               DECIMAL(18,2) NOT NULL DEFAULT 0.00,

  -- keys
  PRIMARY KEY (simulation_id, household_id, sim_clock_datetime),
  
  -- fks to the existing tables
  FOREIGN KEY (simulation_id) REFERENCES world_sim_simulations.simulations (simulation_id) ON DELETE CASCADE
);

-- table to store the weekly activity skeleton templates for agents
CREATE TABLE IF NOT EXISTS world_sim_simulations.agent_weekly_skeleton (
    simulation_id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(64) NOT NULL,
    week_start DATE NOT NULL,
    skeleton_json JSON NOT NULL,
    provenance_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (simulation_id, agent_id, week_start),
    INDEX idx_week_start (week_start),
    FOREIGN KEY (simulation_id) REFERENCES simulations(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);

-- table to store the daily activity block templates for agents
CREATE TABLE IF NOT EXISTS world_sim_simulations.agent_daily_template (
    simulation_id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(64) NOT NULL,
    template_date DATE NOT NULL,
    blocks_json JSON NOT NULL,
    provenance_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (simulation_id, agent_id, template_date),
    INDEX idx_template_date (template_date),
    FOREIGN KEY (simulation_id) REFERENCES simulations(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);

-- table to store the audit records for plan quality and coherence checks
CREATE TABLE IF NOT EXISTS world_sim_simulations.plan_audits (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    plan_id BIGINT UNSIGNED NOT NULL,
    audit_type ENUM('synthesis', 'coherence') NOT NULL,
    input_hash CHAR(64) DEFAULT NULL,
    model_name VARCHAR(100) DEFAULT NULL,
    issues_json JSON,
    edits_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_plan_type (plan_id, audit_type),
    FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE
);



-- table to store the questions asked to agents at times
CREATE TABLE IF NOT EXISTS world_sim_simulations.god_given_to_agent_questions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    simulation_id VARCHAR(64) NOT NULL,
    simulation_timestamp TIMESTAMP NOT NULL,
    agent_id VARCHAR(64) NOT NULL,
    question_text TEXT NOT NULL,
    reasoning_text TEXT NOT NULL,
    answer_text TEXT NOT NULL,
    FOREIGN KEY (simulation_id) REFERENCES simulations(simulation_id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES world_sim_agents.agents(l2_voter_id) ON DELETE CASCADE
);