-- agent location table
DROP TABLE IF EXISTS world_sim_agents.l2_location;

CREATE TABLE IF NOT EXISTS world_sim_agents.l2_location (
    LALVOTERID VARCHAR(64) PRIMARY KEY,
    `Residence_Addresses_AddressLine` VARCHAR(500) NULL,
    `Residence_Addresses_ExtraAddressLine` VARCHAR(500) NULL,
    `Residence_Addresses_City` VARCHAR(255) NULL,
    `Residence_Addresses_State` VARCHAR(2) NULL,
    `Residence_Addresses_Zip` INT NULL,
    `Residence_Addresses_ZipPlus4` INT NULL,
    `Residence_Addresses_DPBC` INT NULL,
    `Residence_Addresses_CheckDigit` INT NULL,
    `Residence_Addresses_HouseNumber` VARCHAR(20) NULL,
    `Residence_Addresses_PrefixDirection` VARCHAR(10) NULL,
    `Residence_Addresses_StreetName` VARCHAR(255) NULL,
    `Residence_Addresses_Designator` VARCHAR(20) NULL,
    `Residence_Addresses_SuffixDirection` VARCHAR(10) NULL,
    `Residence_Addresses_ApartmentNum` VARCHAR(20) NULL,
    `Residence_Addresses_ApartmentType` VARCHAR(20) NULL,
    `Residence_Addresses_CassErrStatCode` VARCHAR(10) NULL,
    `Residence_Addresses_CensusTract` DECIMAL(8,2) NULL,
    `Residence_Addresses_CensusBlockGroup` INT NULL,
    `Residence_Addresses_CensusBlock` INT NULL,
    `Residence_Addresses_Complete_Census_Geocode` VARCHAR(20) NULL,
    `Residence_Addresses_LatLongAccuracy` VARCHAR(10) NULL,
    `Residence_Addresses_Property_Land_Square_Footage` INT NULL,
    `Residence_Addresses_Property_Type` VARCHAR(50) NULL,
    `Mailing_Addresses_AddressLine` VARCHAR(500) NULL,
    `Mailing_Addresses_ExtraAddressLine` VARCHAR(500) NULL,
    `Mailing_Addresses_City` VARCHAR(255) NULL,
    `Mailing_Addresses_State` VARCHAR(2) NULL,
    `Mailing_Addresses_Zip` INT NULL,
    `Mailing_Addresses_ZipPlus4` INT NULL,
    `Mailing_Addresses_DPBC` INT NULL,
    `Mailing_Addresses_CheckDigit` INT NULL,
    `Mailing_Addresses_HouseNumber` VARCHAR(20) NULL,
    `Mailing_Addresses_PrefixDirection` VARCHAR(10) NULL,
    `Mailing_Addresses_StreetName` VARCHAR(255) NULL,
    `Mailing_Addresses_Designator` VARCHAR(20) NULL,
    `Mailing_Addresses_SuffixDirection` VARCHAR(10) NULL,
    `Mailing_Addresses_ApartmentNum` VARCHAR(20) NULL,
    `Mailing_Addresses_ApartmentType` VARCHAR(20) NULL,
    `Mailing_Addresses_CassErrStatCode` VARCHAR(10) NULL,
    `County` VARCHAR(255) NULL,
    `City` VARCHAR(255) NULL,
    `Residence_Addresses_Density` VARCHAR(20) NULL,
    `Residence_Addresses_Property_Home_Square_Footage` INT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
