-- world sim atus database schema
-- Properly normalized with correct primary/foreign keys based on actual data structure

DROP DATABASE IF EXISTS world_sim_atus;
CREATE DATABASE IF NOT EXISTS world_sim_atus CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS world_sim_atus.sum;
DROP TABLE IF EXISTS world_sim_atus.who;
DROP TABLE IF EXISTS world_sim_atus.weights;
DROP TABLE IF EXISTS world_sim_atus.atusact;
DROP TABLE IF EXISTS world_sim_atus.rostec;
DROP TABLE IF EXISTS world_sim_atus.rost;
DROP TABLE IF EXISTS world_sim_atus.resp;
DROP TABLE IF EXISTS world_sim_atus.cps;
DROP TABLE IF EXISTS world_sim_atus.atuscase;
DROP TABLE IF EXISTS world_sim_atus.case_id;
DROP TABLE IF EXISTS world_sim_atus.mapping_codes;

-- mapping codes table
CREATE TABLE IF NOT EXISTS world_sim_atus.mapping_codes (
    major_code VARCHAR(2) NOT NULL,
    major_name VARCHAR(255) NOT NULL,
    tier_code VARCHAR(4) NOT NULL,
    tier_name VARCHAR(255) NOT NULL,
    six_digit_activity_code VARCHAR(6) NOT NULL,
    activity VARCHAR(255) NOT NULL,
    notes TEXT NOT NULL,
    PRIMARY KEY (six_digit_activity_code),
    INDEX idx_major_code (major_code),
    INDEX idx_tier_code (tier_code),
    INDEX idx_activity (activity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- case id table
CREATE TABLE IF NOT EXISTS world_sim_atus.case_id (
    TUCASEID VARCHAR(14) NOT NULL,
    -- Demographics from atussum
    GEMETSTA INTEGER,           -- Geographic: Metro status
    GTMETSTA INTEGER,           -- Geographic: Metro status (alternative)
    PEEDUCA INTEGER,            -- Education level
    PEHSPNON INTEGER,           -- Hispanic/Non-Hispanic
    PTDTRACE INTEGER,           -- Race
    TEAGE INTEGER,              -- Age
    TELFS INTEGER,              -- Labor force status
    TEMJOT INTEGER,             -- Multiple jobs
    TESCHENR INTEGER,           -- School enrollment
    TESCHLVL INTEGER,           -- School level
    TESEX INTEGER,              -- Sex
    TESPEMPNOT INTEGER,         -- Spouse employed
    TRCHILDNUM INTEGER,         -- Number of children
    TRDPFTPT INTEGER,           -- Full/part time status
    TRERNWA INTEGER,            -- Weekly earnings
    TRHOLIDAY INTEGER,          -- Holiday indicator
    TRSPFTPT INTEGER,           -- Spouse full/part time
    TRSPPRES INTEGER,           -- Spouse present
    TRYHHCHILD INTEGER,         -- Children in household
    TUDIARYDAY INTEGER,         -- Diary day of week
    TUFNWGTP DOUBLE,            -- Final weight
    TEHRUSLT INTEGER,           -- Hours usually worked
    TUYEAR INTEGER,             -- Survey year
    TU20FWGT DOUBLE,            -- 2020 weight
    PRIMARY KEY (TUCASEID),
    INDEX idx_year (TUYEAR),
    INDEX idx_age (TEAGE),
    INDEX idx_sex (TESEX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- atuscase table
CREATE TABLE IF NOT EXISTS world_sim_atus.atuscase (
    TUCASEID VARCHAR(14) NOT NULL,
    TR1INTST INTEGER,                -- Interview status 1
    TR2INTST INTEGER,                -- Interview status 2
    TRFNLOUT VARCHAR(10),            -- Final outcome code
    TRINCEN2 INTEGER,                -- Incentive flag
    TUAVGDUR DOUBLE,                 -- Average activity duration
    TUA_ID VARCHAR(10),              -- Interviewer A ID
    TUCPSDP INTEGER,                 -- CPS designation
    TUC_ID VARCHAR(10),              -- Interviewer C ID
    TUDQUAL2 INTEGER,                -- Data quality indicator
    TUINCENT INTEGER,                -- Incentive amount
    TUINTDQUAL INTEGER,              -- Interview quality
    TUINTID VARCHAR(10),             -- Interviewer ID
    TUINTRODATE INTEGER,             -- Interview date (day)
    TUINTROPANMONTH INTEGER,         -- Interview month
    TUINTROPANYEAR INTEGER,          -- Interview year
    TULNGSKL INTEGER,                -- Language skill
    TUTOTACTNO INTEGER,              -- Total number of activities
    TUV_ID VARCHAR(10),              -- Interviewer V ID
    PRIMARY KEY (TUCASEID),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE,
    INDEX idx_interview_year (TUINTROPANYEAR),
    INDEX idx_total_activities (TUTOTACTNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- cps table
CREATE TABLE IF NOT EXISTS world_sim_atus.cps (
    TUCASEID VARCHAR(14) NOT NULL,
    TULINENO INTEGER NOT NULL,      -- Person line number in household
    -- Geographic variables
    GEDIV INTEGER,                  -- Division
    GEMETSTA INTEGER,               -- Metro status
    GEPSEUCL INTEGER,               -- PSU cluster
    GEPSEUST INTEGER,               -- PSU stratum
    GEREG INTEGER,                  -- Region
    GESTFIPS INTEGER,               -- State FIPS
    GTCBSA INTEGER,                 -- CBSA code
    GTCO INTEGER,                   -- County code
    GTMETSTA INTEGER,               -- Metro status
    -- Household variables
    HEFAMINC INTEGER,               -- Family income
    HEHOUSUT INTEGER,               -- Housing unit type
    HEPHONEO INTEGER,               -- Phone ownership
    HETELAVL INTEGER,               -- Telephone available
    HETELHHD INTEGER,               -- Telephone in household
    HETENURE INTEGER,               -- Tenure (own/rent)
    HRHHID BIGINT,                  -- Household ID
    HRHHID2 BIGINT,                 -- Household ID 2
    HRHTYPE INTEGER,                -- Household type
    HRINTSTA INTEGER,               -- Interview status
    HRLONGLK INTEGER,               -- Longitudinal link
    HRMIS INTEGER,                  -- Month in sample (1-8)
    HRMONTH INTEGER,                -- Month
    HRNUMHOU INTEGER,               -- Number in household
    HRSAMPLE INTEGER,               -- Sample ID
    HRSERSUF VARCHAR(4),            -- Sample suffix
    HRYEAR4 INTEGER,                -- Year (4 digit)
    HUBUS INTEGER,                  -- Business indicator
    HUBUSL1 INTEGER,                -- Business line 1
    HUBUSL2 INTEGER,                -- Business line 2
    HUBUSL3 INTEGER,                -- Business line 3
    HUBUSL4 INTEGER,                -- Business line 4
    HUFAMINC INTEGER,               -- Family income
    HUFINAL INTEGER,                -- Final household disposition
    HUHHNUM INTEGER,                -- Household number
    HUINTTYP INTEGER,               -- Interview type
    HUPRSCNT INTEGER,               -- Person count
    HURESPLI INTEGER,               -- Respondent line number
    HUSPNISH INTEGER,               -- Spanish origin
    HXFAMINC INTEGER,               -- Family income imputation
    -- Person variables (selection - there are 265 total columns)
    PEABSPDO INTEGER, PEABSRSN INTEGER, PEAFEVER INTEGER, PEAFNOW INTEGER,
    PEAFWHEN INTEGER, PEAFWHN1 INTEGER, PEAFWHN2 INTEGER, PEAFWHN3 INTEGER,
    PEAFWHN4 INTEGER, PECERT1 INTEGER, PECERT2 INTEGER, PECERT3 INTEGER,
    PECOHAB INTEGER, PECYC INTEGER, PEDADTYP INTEGER, PEDIPGED INTEGER,
    PEDISDRS INTEGER, PEDISEAR INTEGER, PEDISEYE INTEGER, PEDISOUT INTEGER,
    PEDISPHY INTEGER, PEDISREM INTEGER, PEDW4WK INTEGER, PEDWAVL INTEGER,
    PEDWAVR INTEGER, PEDWLKO INTEGER, PEDWLKWK INTEGER, PEDWRSN INTEGER,
    PEDWWK INTEGER, PEDWWNTO INTEGER, PEEDUCA INTEGER, PEERN INTEGER,
    PEERNCOV INTEGER, PEERNH1O INTEGER, PEERNH2 INTEGER, PEERNHRO INTEGER,
    PEERNHRY INTEGER, PEERNLAB INTEGER, PEERNPER INTEGER, PEERNRT INTEGER,
    PEERNUOT INTEGER, PEERNWKP INTEGER, PEFNTVTY INTEGER, PEGR6COR INTEGER,
    PEGRPROF INTEGER, PEHGCOMP INTEGER, PEHRACT1 INTEGER, PEHRACT2 INTEGER,
    PEHRACTT INTEGER, PEHRAVL INTEGER, PEHRFTPT INTEGER, PEHRRSN1 INTEGER,
    PEHRRSN2 INTEGER, PEHRRSN3 INTEGER, PEHRUSL1 INTEGER, PEHRUSL2 INTEGER,
    PEHRUSLT INTEGER, PEHRWANT INTEGER, PEHSPNON INTEGER, PEIO1COW INTEGER,
    PEIO1ICD INTEGER, PEIO1OCD INTEGER, PEIO2COW INTEGER, PEIO2ICD INTEGER,
    PEIO2OCD INTEGER, PEJHRSN INTEGER, PEJHWANT INTEGER, PEJHWKO INTEGER,
    PELAYAVL INTEGER, PELAYDUR INTEGER, PELAYFTO INTEGER, PELAYLK INTEGER,
    PELKAVL INTEGER, PELKDUR INTEGER, PELKFTO INTEGER, PELKLL1O INTEGER,
    PELKLL2O INTEGER, PELKLWO INTEGER, PELKM1 INTEGER, PELNDAD INTEGER,
    PELNMOM INTEGER, PEMARITL INTEGER, PEMJNUM INTEGER, PEMJOT INTEGER,
    PEMLR INTEGER, PEMNTVTY INTEGER, PEMOMTYP INTEGER, PEMS123 INTEGER,
    PENATVTY INTEGER, PENLFACT INTEGER, PENLFJH INTEGER, PENLFRET INTEGER,
    PEPARENT INTEGER, PEPDEMP1 INTEGER, PEPDEMP2 INTEGER, PERET1 INTEGER,
    PERRP INTEGER, PESCHENR INTEGER, PESCHFT INTEGER, PESCHLVL INTEGER,
    PESEX INTEGER, PESPOUSE INTEGER, PRABSREA INTEGER, PRAGNA INTEGER,
    PRCITSHP INTEGER, PRCIVLF INTEGER, PRCOW1 INTEGER, PRCOW2 INTEGER,
    PRCOWPG INTEGER, PRDASIAN INTEGER, PRDISC INTEGER, PRDISFLG INTEGER,
    PRDTCOW1 INTEGER, PRDTCOW2 INTEGER, PRDTHSP INTEGER, PRDTIND1 INTEGER,
    PRDTIND2 INTEGER, PRDTOCC1 INTEGER, PRDTOCC2 INTEGER, PREMP INTEGER,
    PREMPHRS INTEGER, PREMPNOT INTEGER, PRERELG INTEGER, PRERNHLY INTEGER,
    PRERNWA INTEGER, PREXPLF INTEGER, PRFAMNUM INTEGER, PRFAMREL INTEGER,
    PRFAMTYP INTEGER, PRFTLF INTEGER, PRHERNAL INTEGER, PRHRUSL INTEGER,
    PRIMIND1 INTEGER, PRIMIND2 INTEGER, PRINUYER INTEGER, PRIOELG INTEGER,
    PRJOBSEA INTEGER, PRMARSTA INTEGER, PRMJIND1 INTEGER, PRMJIND2 INTEGER,
    PRMJOCC1 INTEGER, PRMJOCC2 INTEGER, PRMJOCGR INTEGER, PRNAGPWS INTEGER,
    PRNAGWS INTEGER, PRNLFSCH INTEGER, PRNMCHLD INTEGER, PRPERTYP INTEGER,
    PRPTHRS INTEGER, PRPTREA INTEGER, PRSJMJ INTEGER, PRTAGE INTEGER,
    PRUNEDUR INTEGER, PRUNTYPE INTEGER, PRWERNAL INTEGER, PRWKSCH INTEGER,
    PRWKSTAT INTEGER, PRWNTJOB INTEGER, PTDTRACE INTEGER, PTHR INTEGER,
    PTNMEMP1 INTEGER, PTNMEMP2 INTEGER, PTOT INTEGER, PTWK INTEGER,
    PUABSOT INTEGER, PUAFEVER INTEGER, PUBUS1 INTEGER, PUBUS2OT INTEGER,
    PUDIS INTEGER, PUDIS1 INTEGER, PUDIS2 INTEGER, PUHROFF1 INTEGER,
    PUHROFF2 INTEGER, PUHROT1 INTEGER, PUHROT2 INTEGER, PUJHDP1O INTEGER,
    PULAY INTEGER, PULAY6M INTEGER, PULAYAVR INTEGER, PULAYDT INTEGER,
    PULINENO INTEGER, PULK INTEGER, PULKAVR INTEGER, PULKDK1 INTEGER,
    PULKDK2 INTEGER, PULKDK3 INTEGER, PULKDK4 INTEGER, PULKM2 INTEGER,
    PULKM3 INTEGER, PULKM4 INTEGER, PULKM5 INTEGER, PULKM6 INTEGER,
    PULKPS1 INTEGER, PULKPS2 INTEGER, PULKPS3 INTEGER, PULKPS4 INTEGER,
    PUPELIG INTEGER, PURETOT INTEGER, PUSLFPRX INTEGER, PUWK INTEGER,
    TRATUSR INTEGER, TUBWGT DOUBLE,
    -- COVID variables (newer years)
    PTCOVID1 INTEGER, PTCOVID2 INTEGER, PTCOVID3 INTEGER, PTCOVID4 INTEGER,
    PTCOVID5W INTEGER, PEPAR1 INTEGER, PEPAR2 INTEGER, PEPAR1TYP INTEGER,
    PEPAR2TYP INTEGER, PRERNMIN INTEGER, PTCOVR1 INTEGER, PTCOVR2 INTEGER,
    PTCOVR3 INTEGER, PTCOVR4 INTEGER, PXCOVR1 INTEGER, PXCOVR2 INTEGER,
    PXCOVR3 INTEGER, PXCOVR4 INTEGER, PTTLWK INTEGER, PTTLWKHR INTEGER,
    PXTLWK INTEGER, PXTLWKHR INTEGER,
    PRIMARY KEY (TUCASEID, TULINENO),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE,
    INDEX idx_tulineno (TULINENO),
    INDEX idx_state (GESTFIPS),
    INDEX idx_year (HRYEAR4)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- resp table
CREATE TABLE IF NOT EXISTS world_sim_atus.resp (
    TUCASEID VARCHAR(14) NOT NULL,
    TULINENO INTEGER NOT NULL,
    -- Employment and earnings
    TESPUHRS INTEGER, TRDTIND1 INTEGER, TRDTOCC1 INTEGER, TRERNHLY INTEGER,
    TRERNUPD INTEGER, TRHERNAL INTEGER, TRHHCHILD INTEGER, TRIMIND1 INTEGER,
    TRMJIND1 INTEGER, TRMJOCC1 INTEGER, TRMJOCGR INTEGER, TRNHHCHILD INTEGER,
    TRNUMHOU INTEGER, TROHHCHILD INTEGER,
    -- Time use variables
    TRTALONE INTEGER, TRTCC INTEGER, TRTHHFAMILY INTEGER, TRTNOCHILD INTEGER,
    TRTNOHH INTEGER, TRTO INTEGER, TRTOHH INTEGER, TRTOHHCHILD INTEGER,
    TRTONHH INTEGER, TRTONHHCHILD INTEGER, TRTSPONLY INTEGER, TRTSPOUSE INTEGER,
    TRTUNMPART INTEGER, TRWERNAL INTEGER, TTHR INTEGER, TTOT INTEGER, TTWK INTEGER,
    -- Survey metadata
    TUABSOT INTEGER, TUYEAR INTEGER,
    -- Additional employment variables
    TEABSRSN INTEGER, TEERN INTEGER, TEERNH1O INTEGER, TEERNH2 INTEGER,
    TEERNHRO INTEGER, TEERNHRY INTEGER, TEERNPER INTEGER, TEERNRT INTEGER,
    TEERNUOT INTEGER, TEERNWKP INTEGER, TEHRFTPT INTEGER, TEHRUSL1 INTEGER,
    TEHRUSL2 INTEGER, TEIO1COW INTEGER, TEIO1ICD INTEGER, TEIO1OCD INTEGER,
    TELAYAVL INTEGER, TELAYLK INTEGER, TELKAVL INTEGER, TELKM1 INTEGER,
    TERET1 INTEGER, TESCHFT INTEGER,
    -- Business and job search
    TUBUS INTEGER, TUBUS1 INTEGER, TUBUS2OT INTEGER, TUBUSL1 INTEGER,
    TUBUSL2 INTEGER, TUBUSL3 INTEGER, TUBUSL4 INTEGER,
    -- Childcare
    TUCC2 INTEGER, TUCC4 INTEGER,
    -- Work-related
    TUFWK INTEGER, TUIO1MFG INTEGER, TUIODP1 INTEGER, TUIODP2 INTEGER,
    TUIODP3 INTEGER, TULAY INTEGER, TULAY6M INTEGER, TULAYAVR INTEGER,
    TULAYDT INTEGER, TULK INTEGER, TULKAVR INTEGER, TULKDK1 INTEGER,
    TULKDK2 INTEGER, TULKDK3 INTEGER, TULKDK4 INTEGER, TULKM2 INTEGER,
    TULKM3 INTEGER, TULKM4 INTEGER, TULKM5 INTEGER, TULKM6 INTEGER,
    TULKPS1 INTEGER, TULKPS2 INTEGER, TULKPS3 INTEGER, TULKPS4 INTEGER,
    TUMONTH INTEGER,
    -- Time with family
    TRTCCC INTEGER, TRTCCTOT INTEGER, TRTCHILD INTEGER, TRTCOC INTEGER,
    TRTFAMILY INTEGER, TRTFRIEND INTEGER, TRTHH INTEGER,
    -- Disability and retirement
    TUDIS2 INTEGER, TURETOT INTEGER,
    -- Additional flags
    TUSPABS INTEGER, TUSPUSFT INTEGER, TUSPWK INTEGER, TREMODR INTEGER,
    TUCC9 INTEGER, TUDIARYDATE INTEGER, TUDIS INTEGER, TUDIS1 INTEGER,
    TRCHILDNUM INTEGER, TUDIARYDAY INTEGER, TRERNWA INTEGER, TRHOLIDAY INTEGER,
    TRSPFTPT INTEGER, TRSPPRES INTEGER, TRDPFTPT INTEGER, TUFNWGTP DOUBLE,
    TESPEMPNOT INTEGER, TESCHLVL INTEGER, TESCHENR INTEGER, TEMJOT INTEGER,
    TELFS INTEGER, TEHRUSLT INTEGER, TRYHHCHILD INTEGER,
    -- Weekly time use
    TRWBMODR INTEGER, TRTALONE_WK INTEGER, TRTCCC_WK INTEGER, TRLVMODR INTEGER,
    -- Elder care
    TRTEC INTEGER, TUECYTD INTEGER, TUELDER INTEGER, TUELFREQ INTEGER,
    TUELNUM INTEGER,
    -- Weight
    TU20FWGT DOUBLE,
    PRIMARY KEY (TUCASEID, TULINENO),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE,
    INDEX idx_tulineno (TULINENO),
    INDEX idx_year (TUYEAR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- rost table
CREATE TABLE IF NOT EXISTS world_sim_atus.rost (
    TUCASEID VARCHAR(14) NOT NULL,
    TULINENO INTEGER NOT NULL,      -- Person line number
    TERRP INTEGER,                  -- Relationship to respondent
    TEAGE INTEGER,                  -- Age
    TESEX INTEGER,                  -- Sex (1=Male, 2=Female)
    PRIMARY KEY (TUCASEID, TULINENO),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE,
    INDEX idx_terrp (TERRP),
    INDEX idx_age (TEAGE),
    INDEX idx_sex (TESEX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- rostec table
CREATE TABLE IF NOT EXISTS world_sim_atus.rostec (
    TUCASEID VARCHAR(14) NOT NULL,
    TUECLNO INTEGER NOT NULL,       -- Elder care person number
    TULINENO INTEGER NOT NULL,      -- Line number (-1 for non-HH)
    TEAGE_EC INTEGER,               -- Age of elder care recipient
    TEELDUR INTEGER,                -- Duration of elder care relationship
    TEELWHO INTEGER,                -- Who provides elder care
    TEELYRS INTEGER,                -- Years providing elder care
    TRELHH INTEGER,                 -- Relationship to HH reference
    PRIMARY KEY (TUCASEID, TUECLNO, TULINENO),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE,
    INDEX idx_teage_ec (TEAGE_EC),
    INDEX idx_tueclno (TUECLNO),
    INDEX idx_tulineno (TULINENO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- atusact table
CREATE TABLE IF NOT EXISTS world_sim_atus.atusact (
    TUCASEID VARCHAR(14) NOT NULL,
    TUACTIVITY_N INTEGER NOT NULL,  -- Activity sequence number (1, 2, 3, ...)
    TUACTDUR24 INTEGER,             -- Activity duration in minutes (0-1440)
    TUCC5 INTEGER,                  -- Childcare flag
    TUCC5B INTEGER,                 -- Childcare flag (alternate)
    TRTCCTOT_LN INTEGER,            -- Total childcare time line
    TRTCC_LN INTEGER,               -- Childcare time line
    TRTCOC_LN INTEGER,              -- Other childcare time line
    TUSTARTTIM VARCHAR(8),          -- Start time (HH:MM:SS)
    TUSTOPTIME VARCHAR(8),          -- Stop time (HH:MM:SS)
    TRCODEP VARCHAR(6),             -- Activity code (links to mapping_codes)
    TRTIER1P INTEGER,               -- Tier 1 activity category
    TRTIER2P INTEGER,               -- Tier 2 activity category
    TUCC8 INTEGER,                  -- Childcare flag 8
    TUCUMDUR INTEGER,               -- Cumulative duration
    TUCUMDUR24 INTEGER,             -- Cumulative duration (24-hour)
    TUACTDUR INTEGER,               -- Activity duration (repeat)
    TR_03CC57 INTEGER,              -- 2003 childcare recode
    TRTO_LN INTEGER,                -- Time with others line
    TRTONHH_LN INTEGER,             -- Time with non-HH line
    TRTOHH_LN INTEGER,              -- Time with other HH line
    TRTHH_LN INTEGER,               -- Time with HH line
    TRTNOHH_LN INTEGER,             -- Time not at home line
    TEWHERE INTEGER,                -- Where activity occurred
    TUCC7 INTEGER,                  -- Childcare flag 7
    TRWBELIG INTEGER,               -- Well-being module eligible
    TRTEC_LN INTEGER,               -- Elder care time line
    TUEC24 INTEGER,                 -- Elder care 24-hour
    TUDURSTOP INTEGER,              -- Duration stop code
    PRIMARY KEY (TUCASEID, TUACTIVITY_N),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE,
    FOREIGN KEY (TRCODEP) REFERENCES world_sim_atus.mapping_codes (six_digit_activity_code) ON DELETE RESTRICT,
    INDEX idx_activity_code (TRCODEP),
    INDEX idx_duration (TUACTDUR24),
    INDEX idx_where (TEWHERE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



-- who table
CREATE TABLE IF NOT EXISTS world_sim_atus.who (
    TUCASEID VARCHAR(14) NOT NULL,
    TULINENO INTEGER NOT NULL,      -- Person line number (or -1)
    TUACTIVITY_N INTEGER NOT NULL,  -- Activity number
    TRWHONA INTEGER NOT NULL,       -- Alone indicator (0/1)
    TUWHO_CODE INTEGER NOT NULL,    -- Who code (18=Spouse, 20=Child, etc., or -1)
    PRIMARY KEY (TUCASEID, TULINENO, TUACTIVITY_N, TUWHO_CODE),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE,
    FOREIGN KEY (TUCASEID, TUACTIVITY_N) REFERENCES world_sim_atus.atusact (TUCASEID, TUACTIVITY_N) ON DELETE CASCADE,
    INDEX idx_activity (TUACTIVITY_N),
    INDEX idx_who_code (TUWHO_CODE),
    INDEX idx_alone (TRWHONA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- weights table
CREATE TABLE IF NOT EXISTS world_sim_atus.weights (
    TUCASEID VARCHAR(14) NOT NULL,
    TUFNWGTP001 DOUBLE, TUFNWGTP002 DOUBLE, TUFNWGTP003 DOUBLE, TUFNWGTP004 DOUBLE,
    TUFNWGTP005 DOUBLE, TUFNWGTP006 DOUBLE, TUFNWGTP007 DOUBLE, TUFNWGTP008 DOUBLE,
    TUFNWGTP009 DOUBLE, TUFNWGTP010 DOUBLE, TUFNWGTP011 DOUBLE, TUFNWGTP012 DOUBLE,
    TUFNWGTP013 DOUBLE, TUFNWGTP014 DOUBLE, TUFNWGTP015 DOUBLE, TUFNWGTP016 DOUBLE,
    TUFNWGTP017 DOUBLE, TUFNWGTP018 DOUBLE, TUFNWGTP019 DOUBLE, TUFNWGTP020 DOUBLE,
    TUFNWGTP021 DOUBLE, TUFNWGTP022 DOUBLE, TUFNWGTP023 DOUBLE, TUFNWGTP024 DOUBLE,
    TUFNWGTP025 DOUBLE, TUFNWGTP026 DOUBLE, TUFNWGTP027 DOUBLE, TUFNWGTP028 DOUBLE,
    TUFNWGTP029 DOUBLE, TUFNWGTP030 DOUBLE, TUFNWGTP031 DOUBLE, TUFNWGTP032 DOUBLE,
    TUFNWGTP033 DOUBLE, TUFNWGTP034 DOUBLE, TUFNWGTP035 DOUBLE, TUFNWGTP036 DOUBLE,
    TUFNWGTP037 DOUBLE, TUFNWGTP038 DOUBLE, TUFNWGTP039 DOUBLE, TUFNWGTP040 DOUBLE,
    TUFNWGTP041 DOUBLE, TUFNWGTP042 DOUBLE, TUFNWGTP043 DOUBLE, TUFNWGTP044 DOUBLE,
    TUFNWGTP045 DOUBLE, TUFNWGTP046 DOUBLE, TUFNWGTP047 DOUBLE, TUFNWGTP048 DOUBLE,
    TUFNWGTP049 DOUBLE, TUFNWGTP050 DOUBLE, TUFNWGTP051 DOUBLE, TUFNWGTP052 DOUBLE,
    TUFNWGTP053 DOUBLE, TUFNWGTP054 DOUBLE, TUFNWGTP055 DOUBLE, TUFNWGTP056 DOUBLE,
    TUFNWGTP057 DOUBLE, TUFNWGTP058 DOUBLE, TUFNWGTP059 DOUBLE, TUFNWGTP060 DOUBLE,
    TUFNWGTP061 DOUBLE, TUFNWGTP062 DOUBLE, TUFNWGTP063 DOUBLE, TUFNWGTP064 DOUBLE,
    TUFNWGTP065 DOUBLE, TUFNWGTP066 DOUBLE, TUFNWGTP067 DOUBLE, TUFNWGTP068 DOUBLE,
    TUFNWGTP069 DOUBLE, TUFNWGTP070 DOUBLE, TUFNWGTP071 DOUBLE, TUFNWGTP072 DOUBLE,
    TUFNWGTP073 DOUBLE, TUFNWGTP074 DOUBLE, TUFNWGTP075 DOUBLE, TUFNWGTP076 DOUBLE,
    TUFNWGTP077 DOUBLE, TUFNWGTP078 DOUBLE, TUFNWGTP079 DOUBLE, TUFNWGTP080 DOUBLE,
    TUFNWGTP081 DOUBLE, TUFNWGTP082 DOUBLE, TUFNWGTP083 DOUBLE, TUFNWGTP084 DOUBLE,
    TUFNWGTP085 DOUBLE, TUFNWGTP086 DOUBLE, TUFNWGTP087 DOUBLE, TUFNWGTP088 DOUBLE,
    TUFNWGTP089 DOUBLE, TUFNWGTP090 DOUBLE, TUFNWGTP091 DOUBLE, TUFNWGTP092 DOUBLE,
    TUFNWGTP093 DOUBLE, TUFNWGTP094 DOUBLE, TUFNWGTP095 DOUBLE, TUFNWGTP096 DOUBLE,
    TUFNWGTP097 DOUBLE, TUFNWGTP098 DOUBLE, TUFNWGTP099 DOUBLE, TUFNWGTP100 DOUBLE,
    TUFNWGTP101 DOUBLE, TUFNWGTP102 DOUBLE, TUFNWGTP103 DOUBLE, TUFNWGTP104 DOUBLE,
    TUFNWGTP105 DOUBLE, TUFNWGTP106 DOUBLE, TUFNWGTP107 DOUBLE, TUFNWGTP108 DOUBLE,
    TUFNWGTP109 DOUBLE, TUFNWGTP110 DOUBLE, TUFNWGTP111 DOUBLE, TUFNWGTP112 DOUBLE,
    TUFNWGTP113 DOUBLE, TUFNWGTP114 DOUBLE, TUFNWGTP115 DOUBLE, TUFNWGTP116 DOUBLE,
    TUFNWGTP117 DOUBLE, TUFNWGTP118 DOUBLE, TUFNWGTP119 DOUBLE, TUFNWGTP120 DOUBLE,
    TUFNWGTP121 DOUBLE, TUFNWGTP122 DOUBLE, TUFNWGTP123 DOUBLE, TUFNWGTP124 DOUBLE,
    TUFNWGTP125 DOUBLE, TUFNWGTP126 DOUBLE, TUFNWGTP127 DOUBLE, TUFNWGTP128 DOUBLE,
    TUFNWGTP129 DOUBLE, TUFNWGTP130 DOUBLE, TUFNWGTP131 DOUBLE, TUFNWGTP132 DOUBLE,
    TUFNWGTP133 DOUBLE, TUFNWGTP134 DOUBLE, TUFNWGTP135 DOUBLE, TUFNWGTP136 DOUBLE,
    TUFNWGTP137 DOUBLE, TUFNWGTP138 DOUBLE, TUFNWGTP139 DOUBLE, TUFNWGTP140 DOUBLE,
    TUFNWGTP141 DOUBLE, TUFNWGTP142 DOUBLE, TUFNWGTP143 DOUBLE, TUFNWGTP144 DOUBLE,
    TUFNWGTP145 DOUBLE, TUFNWGTP146 DOUBLE, TUFNWGTP147 DOUBLE, TUFNWGTP148 DOUBLE,
    TUFNWGTP149 DOUBLE, TUFNWGTP150 DOUBLE, TUFNWGTP151 DOUBLE, TUFNWGTP152 DOUBLE,
    TUFNWGTP153 DOUBLE, TUFNWGTP154 DOUBLE, TUFNWGTP155 DOUBLE, TUFNWGTP156 DOUBLE,
    TUFNWGTP157 DOUBLE, TUFNWGTP158 DOUBLE, TUFNWGTP159 DOUBLE, TUFNWGTP160 DOUBLE,
    PRIMARY KEY (TUCASEID),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- sum table
CREATE TABLE IF NOT EXISTS world_sim_atus.sum (
    TUCASEID VARCHAR(14) NOT NULL,
    activity_code VARCHAR(6) NOT NULL,
    minutes INTEGER NOT NULL,        -- Time spent in minutes
    PRIMARY KEY (TUCASEID, activity_code),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE,
    FOREIGN KEY (activity_code) REFERENCES world_sim_atus.mapping_codes (six_digit_activity_code) ON DELETE RESTRICT,
    INDEX idx_activity_code (activity_code),
    INDEX idx_minutes (minutes)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;





-- strata def table
CREATE TABLE IF NOT EXISTS world_sim_atus.strata_def (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    definition JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- case stratum table
CREATE TABLE IF NOT EXISTS world_sim_atus.case_stratum (
    TUCASEID VARCHAR(14) NOT NULL,
    stratum_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (TUCASEID),
    FOREIGN KEY (TUCASEID) REFERENCES world_sim_atus.case_id (TUCASEID) ON DELETE CASCADE,
    FOREIGN KEY (stratum_id) REFERENCES world_sim_atus.strata_def (id) ON DELETE CASCADE,
    INDEX idx_stratum (stratum_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- operator map table
CREATE TABLE IF NOT EXISTS world_sim_atus.operator_map (
    six_digit_activity_code VARCHAR(6) NOT NULL,
    operator_group VARCHAR(50) NOT NULL,
    default_location ENUM('home', 'out') DEFAULT NULL,
    typical_minutes_p50 INT DEFAULT NULL,
    cooldown_days INT DEFAULT NULL,
    weekly_quota INT DEFAULT NULL,
    prereq_flags JSON DEFAULT NULL,
    PRIMARY KEY (six_digit_activity_code),
    FOREIGN KEY (six_digit_activity_code) REFERENCES world_sim_atus.mapping_codes (six_digit_activity_code) ON DELETE CASCADE,
    INDEX idx_operator_group (operator_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- hourly mix table
CREATE TABLE IF NOT EXISTS world_sim_atus.hourly_mix (
    stratum_id INT UNSIGNED NOT NULL,
    dow TINYINT UNSIGNED NOT NULL,
    hour TINYINT UNSIGNED NOT NULL,
    operator_group VARCHAR(50) NOT NULL,
    probability DOUBLE NOT NULL,
    sample_n INT UNSIGNED NOT NULL,
    weight_sum DOUBLE NOT NULL,
    PRIMARY KEY (stratum_id, dow, hour, operator_group),
    FOREIGN KEY (stratum_id) REFERENCES world_sim_atus.strata_def (id) ON DELETE CASCADE,
    INDEX idx_operator (operator_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- duration stats table
CREATE TABLE IF NOT EXISTS world_sim_atus.duration_stats (
    stratum_id INT UNSIGNED NOT NULL,
    dow TINYINT UNSIGNED NOT NULL,
    operator_group VARCHAR(50) NOT NULL,
    mean_minutes DOUBLE NOT NULL,
    sd_minutes DOUBLE DEFAULT NULL,
    p10_minutes INT DEFAULT NULL,
    p50_minutes INT DEFAULT NULL,
    p90_minutes INT DEFAULT NULL,
    sample_n INT UNSIGNED NOT NULL,
    weight_sum DOUBLE NOT NULL,
    PRIMARY KEY (stratum_id, dow, operator_group),
    FOREIGN KEY (stratum_id) REFERENCES world_sim_atus.strata_def (id) ON DELETE CASCADE,
    INDEX idx_operator (operator_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- transitions table
CREATE TABLE IF NOT EXISTS world_sim_atus.transitions (
    stratum_id INT UNSIGNED NOT NULL,
    hour TINYINT UNSIGNED NOT NULL,
    from_operator VARCHAR(50) NOT NULL,
    to_operator VARCHAR(50) NOT NULL,
    probability DOUBLE NOT NULL,
    sample_n INT UNSIGNED NOT NULL,
    PRIMARY KEY (stratum_id, hour, from_operator, to_operator),
    FOREIGN KEY (stratum_id) REFERENCES world_sim_atus.strata_def (id) ON DELETE CASCADE,
    INDEX idx_from_to (from_operator, to_operator)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- social where table
CREATE TABLE IF NOT EXISTS world_sim_atus.social_where (
    stratum_id INT UNSIGNED NOT NULL,
    hour TINYINT UNSIGNED NOT NULL,
    operator_group VARCHAR(50) NOT NULL,
    home_prob DOUBLE DEFAULT NULL,
    with_spouse DOUBLE DEFAULT NULL,
    with_child DOUBLE DEFAULT NULL,
    with_friend DOUBLE DEFAULT NULL,
    alone_prob DOUBLE DEFAULT NULL,
    sample_n INT UNSIGNED NOT NULL,
    weight_sum DOUBLE NOT NULL,
    PRIMARY KEY (stratum_id, hour, operator_group),
    FOREIGN KEY (stratum_id) REFERENCES world_sim_atus.strata_def (id) ON DELETE CASCADE,
    INDEX idx_operator (operator_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- weekly presence table
CREATE TABLE IF NOT EXISTS world_sim_atus.weekly_presence (
    stratum_id INT UNSIGNED NOT NULL,
    operator_group VARCHAR(50) NOT NULL,
    presence_rate DOUBLE NOT NULL,
    mean_minutes_per_week DOUBLE NOT NULL,
    sample_n INT UNSIGNED NOT NULL,
    weight_sum DOUBLE NOT NULL,
    PRIMARY KEY (stratum_id, operator_group),
    FOREIGN KEY (stratum_id) REFERENCES world_sim_atus.strata_def (id) ON DELETE CASCADE,
    INDEX idx_operator (operator_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
